"""pdm: sensor anomaly detection + maintenance scheduling on synthetic plant data.

All data in this package is synthetic and generated by a seeded generator
(`pdm.data`). Nothing here is real telemetry.
"""

__version__ = "0.1.0"
